favicon: null
name: damianwriter
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.3191489
  brandStrength: 0.8446808
  lightness: 0
  brandColors:
    - '#0B0604'
    - '#F1CF5A'
    - '#FFFDF2'
    - '#4B1F0D'
    - '#C6661F'
  rhythmicContrast: 0.5234042
typography_spectrum: 0.193617
layout_spectrum: 0.7893617
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
